version: 1
update_configs:
  # Update your Gemfile (& lockfiles) as soon as
  # new versions are published to the RubyGems registry
  - package_manager: "ruby:bundler"
    directory: "/"
    update_schedule: "live"
    # Ignore rubocop
    ignored_updates:
        - match:
            dependency_name: "rubocop"